artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: nazmul0087/ct-kidney-dataset-normal-cyst-tumor-and-stone
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

evaluation:
  root_dir: artifacts/evaluation
  path_of_model: artifacts/training/model.h5
  data_root: artifacts/data_ingestion
  mlflow_uri: https://dagshub.com/saksham-1304/Kidney-Disease-Classification-System.mlflow
